---
title: "ESM 244 Task One"
author: "Jaden Orli"
date: last-modified
execute: 
  eval: true
format:
  html:
    theme: minty
    toc: true
    toc-title: "Table of Contents:"
editor:
  chunk_output_type: inline
embed-resources: true
---

# I. Background



# II. Set Up

## a) Load Libraries

```{r}
#this clears out the environment
rm(list = ls())

#load necessary data packages
library(tidyverse)
library(readxl)
library(stringr)
library(here)
library(lubridate)
library(patchwork)

```


## b) Read Data

```{r}
#read in the xlsx file with the data on the amphibians 
amphibians <- read_xlsx(here("data", "sierra_amphibians.xlsx"))

#clean and tidy the data
amphibians_clean <- amphibians %>%
  rename_with(~ str_remove(., "^amphibian_")) %>% #remove the "amphibian_" portion from the column headers
  mutate(year = lubridate::year(survey_date)) #create a new column with just the year
  
```



```{r}
#create a new dataframe with just the mountain yellow-legged frog (Rana muscosa)
ramu <- amphibians_clean %>%
  filter(species == "RAMU") %>% #only select the desired species (RAMU)
  filter(life_stage != "EggMass") %>% #remove the rows where the life stage is egg mass 
  select(species, life_stage, state, number, year) #select only the necessary columns 

#create a new dataframe with the summary of total individuals per year
ramu_sum <- ramu %>%
  group_by(year, life_stage) %>% #group the data by the year and life stage 
  summarize(total_count = sum(number)) #calculate the total number of individuals seen in that year for each life stage

```


```{r}
#create a graph to visualize the number of mountain yellow-legged frogs of each life stage found for each year from 1995 to 2002
ramu_life_year <- ggplot(ramu_sum, aes(x = year, y = total_count, group = life_stage)) +
  geom_line(aes(color = life_stage))

ramu_life_year
  
```

